# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Hdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdd_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=200)),
                ('processor_model', models.CharField(max_length=64)),
                ('processor_frequency', models.IntegerField()),
                ('ram_value', models.IntegerField()),
                ('display_size', models.FloatField()),
                ('videocard', models.CharField(max_length=128)),
                ('video_memory_value', models.IntegerField()),
                ('weight', models.FloatField()),
                ('optical_drive', models.BooleanField()),
                ('lte_4g', models.BooleanField()),
                ('bluetooth', models.BooleanField()),
                ('wi_fi', models.BooleanField()),
                ('price', models.IntegerField()),
                ('hdd_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic_catalog.Hdd')),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technic_catalog.Color')),
            ],
        ),
    ]
