# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technic_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='cards_images'),
        ),
    ]
