# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technic_catalog', '0003_auto_20171015_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hdd_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_color',
        ),
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='technic_catalog.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hdd',
            name='product',
            field=models.ForeignKey(default=256, on_delete=django.db.models.deletion.CASCADE, to='technic_catalog.Product'),
            preserve_default=False,
        ),
    ]
