# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technic_catalog', '0004_auto_20171015_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='technic_catalog.Product'),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='technic_catalog.Product'),
        ),
    ]
