# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technic_catalog', '0005_auto_20171015_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdd',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hdd_capacity', to='technic_catalog.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
    ]
